[package]
name = "learn_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashu-float = "0.4.3"
dashu-int = "0.4.1"
itertools = "0.12.1"
multimap = "0.10.0"
rand = "0.9.0-alpha.1"
